### ISSUE TITLE
Migrate to Zenika Open Source organization

### ISSUE THREAD

**Issue by jeanphibaconnais** [zenika-open-source/sustainable-business-design#1]
We can imagine migrate the project to Zenika open source organization

For the open source, we can add a contributing.md and add a Zenika badge 🎉

**Comment by jeanphibaconnais** [comment]
this point is done  : We can imagine migrate the project to Zenika open source organization

**Comment by mguilliot** [comment]
Contributing.md is initiated

**Comment by jeanphibaconnais** [comment]
I close this issue, the file is created and the project is migrated
